import React, { Suspense, useCallback, useEffect, useRef, useState } from 'react';

import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { ContactShadows, Html, OrbitControls, RoundedBox } from '@react-three/drei';
import { Vector3, Group } from 'three';

import { ArrowUpRight, Box, ChevronRight, Coffee, Compass, Focus, HelpCircle, Leaf, Maximize2, Minus, Pause, Play, Plus, Radio, RotateCcw, Sparkles, Sun, Users, X } from 'lucide-react';
import './style.css';
import { IdeaBoard } from './IdeaBoard';

import { people, workers, everyone, rooms, profiles, originalTeam, desks, location, stateIcons } from './simulation/model';
import type { Person, Agent, Room, CeoCommand } from './simulation/model';
import { useSimulation } from './simulation/useSimulation';
import { AgentPanel, CEOPanel, WorkflowCard, WorkflowWindow } from './WorkflowPanel';
import WorldExpansion from './WorldExpansion';
import './workflow.css';
import './office-theme.css';
import './management.css';
type FocusRequest = { point: [number, number, number]; key: number; home?: boolean; room?: boolean; zoom?: number };

function Block({p=[0,0,0], s=[1,1,1], c='#fff', r=0, ...props}:{p?:[number,number,number];s?:[number,number,number];c?:string;r?:number;[key:string]:unknown}){
 return <mesh position={p} rotation={[0,r,0]} castShadow receiveShadow {...props}><boxGeometry args={s}/><meshStandardMaterial color={c} roughness={.72}/></mesh>;
}
function Round({p=[0,0,0],s=[1,1,1],c='#fff',radius=.09}:{p?:[number,number,number];s?:[number,number,number];c?:string;radius?:number}){return <RoundedBox position={p} args={s} radius={radius} smoothness={2} castShadow receiveShadow><meshStandardMaterial color={c} roughness={.8}/></RoundedBox>}
function Ball({p,s=.1,c='#fff'}:{p:[number,number,number];s?:number;c?:string}){return <mesh position={p} castShadow><sphereGeometry args={[s,12,10]}/><meshStandardMaterial color={c}/></mesh>}
function Cylinder({p,r=.1,h=.3,c='#fff'}:{p:[number,number,number];r?:number;h?:number;c?:string}){return <mesh position={p} castShadow receiveShadow><cylinderGeometry args={[r,r*.93,h,12]}/><meshStandardMaterial color={c}/></mesh>}
function Plant({p=[0,0,0],scale=1}:{p?:[number,number,number];scale?:number}){return <group position={p} scale={scale}><Cylinder p={[0,.22,0]} r={.22} h={.4} c="#e4ad8e"/><Cylinder p={[0,.43,0]} r={.19} h={.035} c="#76644e"/>{[0,1,2,3,4].map(i=><group key={i} position={[0,.5,0]} rotation={[.3+ i*.11,i*2.4,.5]}><mesh position={[0,.22,0]} scale={[.13,.4,.13]} castShadow><sphereGeometry args={[1,7,6]}/><meshStandardMaterial color={i%2?'#729b6e':'#a1bd7c'}/></mesh></group>)}</group>}
function Mug({p=[0,0,0],c='#e6c373'}:{p?:[number,number,number];c?:string}){return <group position={p}><Cylinder p={[0,.09,0]} r={.075} h={.18} c={c}/><Cylinder p={[0,.183,0]} r={.056} h={.005} c="#694d3b"/><mesh position={[.085,.1,0]}><torusGeometry args={[.045,.018,6,12]}/><meshStandardMaterial color={c}/></mesh></group>}
function Drawing({p=[0,0,0],kind='bridge'}:{p?:[number,number,number];kind?:string}){return <group position={p}><Block s={[1.4,.8,.04]} c="#d4b891"/><Block p={[0,0,.026]} s={[1.29,.69,.01]} c="#eef2e3"/>{kind==='bridge'?<><Block p={[0,-.03,.04]} s={[1.07,.028,.02]} c="#648a88"/>{[-.37,.37].map(x=><Block key={x} p={[x,-.14,.04]} s={[.045,.25,.02]} c="#648a88"/>)}{[-.35,-.17,0,.17,.35].map(x=><Block key={x} p={[x,.04,.04]} s={[.022,.12,.02]} c="#8dada5"/>)}</>:<>{[0,1,2,3,4].map(i=><Block key={i} p={[-.4+i*.2,-.16+i*.05,.04]} s={[.1,.13+i*.09,.02]} c={i%2?'#b6c995':'#7daba4'}/>)}</>}<Block p={[-.35,.23,.04]} s={[.42,.025,.02]} c="#a0aaa0"/></group>}
function Chair({p,c='#79a39b',r=0}:{p:[number,number,number];c?:string;r?:number}){return <group position={p} rotation={[0,r,0]}><Round p={[0,.55,0]} s={[.65,.14,.58]} c={c}/><Round p={[0,.9,.23]} s={[.65,.64,.13]} c={c}/><Cylinder p={[0,.25,0]} h={.5} r={.06} c="#626f65"/><Block p={[0,.05,0]} s={[.55,.05,.07]} c="#626f65"/><Block p={[0,.05,0]} s={[.07,.05,.5]} c="#626f65"/></group>}
function Desk({name}:{name:Person}){const [x,z]=name==='Eco'?[2.3,-2.3]:desks[name];return <group position={[x,0,z-.7]}><Round p={[0,.96,0]} s={[2.2,.15,1.15]} c="#dfbd93"/>{[-.88,.88].map(x=><Block key={x} p={[x,.47,0]} s={[.09,.9,.85]} c="#e8e9dd"/>)}<Block p={[.4,1.45,-.3]} s={[1.02,.65,.09]} c="#415c59"/><Block p={[.4,1.45,-.248]} s={[.91,.53,.01]} c="#b6d9c7"/>{[0,1,2].map(i=><Block key={i} p={[.17+i*.17,1.37+i*.045,-.235]} s={[.04,.15+i*.07,.01]} c="#5c9787"/>)}<Block p={[.4,1.14,-.3]} s={[.06,.3,.07]} c="#526b63"/><Block p={[.4,1.06,-.2]} s={[.4,.035,.3]} c="#526b63"/><Block p={[.37,1.065,.26]} s={[.69,.035,.23]} c="#e7eee2"/>{[0,1,2].map(i=><Block key={i} p={[.37,1.085,.2+i*.055]} s={[.57,.008,.018]} c="#aebfb4"/>)}<Block p={[-.62,1.055,.19]} s={[.43,.012,.42]} c="#f4f2e7" r={.15}/><Mug p={[-.8,1.04,-.29]} c={profiles[name].color}/><Chair p={[0,0,1.2]} c={profiles[name].color}/></group>}
function Bridge({small=false,spans=3,span=40,width=12,depth=2.4}:{small?:boolean;spans?:number;span?:number;width?:number;depth?:number}){const length=2.45*Math.max(.83,Math.min(1.18,span/40)),deck=.7*Math.max(.83,Math.min(1.2,width/12)),boxHeight=.17*Math.max(.8,Math.min(1.25,depth/2.4));return <group scale={small?.5:1}>{Array.from({length:Math.max(1,spans-1)},(_,i)=>-length/2+(i+1)*length/spans).map(x=><group key={x}><Block p={[x,.2,0]} s={[.35,.1,.52]} c="#b2c2b7"/><Block p={[x,.49,0]} s={[.15,.55,.27]} c="#d8dfd0"/><Block p={[x,.73,0]} s={[.39,.1,.48]} c="#c3d1c1"/></group>)}<Block p={[0,.85,0]} s={[length,boxHeight,deck*.82]} c="#8bafa1"/>{[-length/2,length/2].map(x=><group key={x}>{[-.15,.15].map(z=><Block key={z} p={[x,.85,z]} s={[.01,.095,.19]} c="#456e62"/>)}</group>)}<Block p={[0,.96,0]} s={[length+.1,.065,deck]} c="#d9dfcc"/>{[-deck*.45,deck*.45].map(z=><group key={z}><Block p={[0,1.12,z]} s={[length+.08,.035,.025]} c="#5f8c7f"/>{[-1.2,-.8,-.4,0,.4,.8,1.2].map(x=><Block key={x} p={[x*length/2.45,1.055,z]} s={[.024,.17,.025]} c="#6f988b"/>)}</group>)}{[-1,-.5,0,.5,1].map(x=><Block key={x} p={[x*length/2.45,.997,0]} s={[.22,.008,.025]} c="#f6f5d8"/>)}</group>}
function Office({onBridge,spans,span,width,depth}:{onBridge:()=>void;spans:number;span:number;width:number;depth:number}){return <group>
 <Round p={[0,-.28,0]} s={[11.6,.5,8.9]} c="#b6c8b6" radius={.16}/><Block p={[0,-.012,0]} s={[11.3,.07,8.6]} c="#e4ddc8"/>
 {Array.from({length:18},(_,i)=><Block key={i} p={[0,.027,-4.2+i*.48]} s={[11.25,.004,.014]} c="#d3ccb7"/>)}
 <Block p={[0,1.55,-4.35]} s={[11.6,3.55,.18]} c="#eadbba"/><Block p={[-5.7,1.55,0]} s={[.18,3.55,8.6]} c="#d9e3d3"/>
 <Block p={[0,3.35,-4.35]} s={[11.65,.12,.25]} c="#f6edd4"/><Block p={[-5.7,3.35,0]} s={[.25,.12,8.7]} c="#eff1df"/>
 <Block p={[0,.16,-4.22]} s={[11.3,.24,.065]} c="#d4c6aa"/><Block p={[-5.57,.16,0]} s={[.065,.24,8.5]} c="#bdcdbb"/>
 <group position={[-5.55,2.1,-1.7]} rotation={[0,Math.PI/2,0]}><Block s={[3.7,1.9,.1]} c="#f4efdb"/><Block p={[0,0,.07]} s={[3.45,1.65,.05]} c="#bddece"/><Block p={[0,0,.11]} s={[.075,1.7,.06]} c="#f6f3dd"/><Block p={[0,0,.11]} s={[3.48,.075,.06]} c="#f6f3dd"/><Block p={[0,-.91,.2]} s={[3.85,.12,.44]} c="#f1ead3"/></group>
 <Drawing p={[-3.75,2.48,-4.22]}/><Drawing p={[-.95,2.48,-4.22]} kind="graph"/>
 <group position={[2.55,2.45,-4.19]}><Block s={[3.3,1.32,.08]} c="#90a99a"/><Block p={[0,0,.055]} s={[3.16,1.18,.03]} c="#f4f0dd"/><IdeaBoard/></group>
 {originalTeam.map(name=><Desk key={name} name={name}/>)}<Desk name="Check"/>
 <group position={[-.3,0,.05]} onClick={e=>{e.stopPropagation();onBridge()}} onPointerOver={()=>document.body.style.cursor='pointer'} onPointerOut={()=>document.body.style.cursor='auto'}><Round p={[0,.82,0]} s={[3.3,.16,1.65]} c="#d1ae86"/>{[-1.3,1.3].map(x=><Block key={x} p={[x,.4,0]} s={[.13,.8,1.3]} c="#6c968b"/>)}<Block p={[0,.915,0]} s={[2.9,.025,1.3]} c="#739f95"/><group position={[0,.94,0]}><Bridge spans={spans} span={span} width={width} depth={depth}/></group><Html position={[0,2.27,0]} center distanceFactor={16}><button className="model-label" onClick={onBridge}><Box size={12}/> LITTLE BRIDGE, BIG IDEAS <ChevronRight size={12}/></button></Html></group>
 <group position={[-4.92,0,.1]}><Round p={[0,.6,0]} s={[.95,1.2,1.5]} c="#e8bd94"/><Block p={[0,1.23,0]} s={[1.08,.09,1.58]} c="#f3ead3"/><Round p={[0,1.64,-.3]} s={[.66,.72,.61]} c="#516d63"/><Block p={[.345,1.62,-.3]} s={[.035,.37,.42]} c="#283e37"/><Mug p={[.35,1.29,-.3]}/><Cylinder p={[0,2.05,-.3]} r={.16} h={.15} c="#a88963"/><Mug p={[0,1.29,.5]} c="#f4f2df"/></group>
 <group position={[-3.95,0,2.9]}><Round p={[0,.34,0]} s={[2.28,.56,1.03]} c="#c89b79"/><Round p={[0,.88,-.43]} s={[2.28,.82,.23]} c="#dfb090"/>{[-1.03,1.03].map(x=><Round key={x} p={[x,.66,0]} s={[.28,.6,1.07]} c="#d9a786"/>)}{[-.5,.5].map(x=><Round key={x} p={[x,.65,0]} s={[.89,.22,.86]} c="#e7bc98"/>)}<Round p={[-.64,.92,-.14]} s={[.42,.43,.18]} c="#dce1b8"/><Round p={[.66,.92,-.14]} s={[.42,.43,.18]} c="#9fb79b"/></group>
 <Cylinder p={[-2.5,.42,3.47]} r={.42} h={.08} c="#e9c69c"/><Cylinder p={[-2.5,.21,3.47]} r={.055} h={.4} c="#687e69"/><Mug p={[-2.5,.47,3.47]}/>
 <group position={[2.45,0,2.15]}><Round p={[0,.015,0]} s={[3.7,.035,2.8]} c="#b9cbbb"/><Round p={[0,.9,0]} s={[2.4,.15,1.2]} c="#e4bf91"/>{[-.85,.85].map(x=><Block key={x} p={[x,.43,0]} s={[.09,.85,.75]} c="#eeeadd"/>)}<Chair p={[-.65,0,.9]} c="#8caaa1"/><Chair p={[.65,0,.9]} c="#8caaa1"/><Chair p={[-.65,0,-.85]} r={Math.PI} c="#8caaa1"/><Chair p={[.65,0,-.85]} r={Math.PI} c="#8caaa1"/><Block p={[.35,.989,0]} s={[.55,.015,.43]} c="#f6f2dc" r={.2}/><Mug p={[-.6,.98,0]}/><Plant p={[.83,.98,-.2]} scale={.4}/></group>
 <group position={[5.02,0,-2.4]}><Round p={[0,.83,0]} s={[.85,1.65,1]} c="#59756c"/>{[0,1,2,3,4].map(i=><group key={i}><Block p={[0,.28+i*.26,.52]} s={[.68,.18,.04]} c="#3c5952"/><Ball p={[.22,.28+i*.26,.55]} s={.025} c="#b6e8a0"/><Block p={[-.08,.28+i*.26,.55]} s={[.3,.018,.015]} c="#8ca799"/></group>)}<Plant p={[0,1.68,0]} scale={.55}/></group>
 <group position={[-5.06,0,2.62]}><Block p={[0,1.23,0]} s={[.64,2.46,1.4]} c="#c3aa84"/>{[.15,.85,1.55,2.25].map(y=><Block key={y} p={[.06,y,0]} s={[.72,.07,1.43]} c="#ecd2a9"/>)}{[0,1,2,3,4].map(i=><Block key={i} p={[.15,1.15,-.47+i*.18]} s={[.45,.5,.12]} c={['#93afa1','#dba886','#e9d7a1','#77939a','#b6c193'][i]}/>)}<group position={[.4,1.59,0]} rotation={[0,Math.PI/2,0]}><Bridge small/></group></group>
 <Plant p={[4.85,0,3.4]} scale={1.3}/><Plant p={[-4.9,0,-3.65]} scale={1.15}/><Plant p={[4.45,0,-3.6]} scale={.8}/>
 <group position={[1.8,1.01,2.15]}><Block s={[.48,.025,.36]} c="#9c8bb1"/><Block p={[0,.019,0]} s={[.4,.01,.28]} c="#f4f0dd"/></group>
 <group position={[3.1,1.025,2.2]}><Block s={[.26,.04,.37]} c="#cfac51"/><Block p={[0,.025,-.1]} s={[.19,.01,.08]} c="#466b62"/>{[0,1,2].map(i=><Block key={i} p={[-.07+i*.07,.026,.04]} s={[.04,.01,.1]} c="#f6e5a9"/>)}</group>
 <group position={[4.8,.05,1.03]}><Cylinder p={[0,.05,0]} r={.36} h={.1} c="#cfb693"/><Block p={[0,.46,0]} s={[.2,.8,.25]} c="#b3c3b5"/><Block p={[0,.84,0]} s={[.65,.12,.33]} c="#b3c3b5"/></group>
 </group>}

function Character({agent,paused,speed,labels,onSelect,positions,simTime}:{agent:Agent;paused:boolean;speed:number;labels:boolean;onSelect:(n:Person)=>void;positions:React.RefObject<Record<Person,Vector3>>;simTime:number}){
 const name=agent.name, place=agent.destination, moving=agent.state==='WALKING';
 const root=useRef<Group>(null),body=useRef<Group>(null),left=useRef<Group>(null),right=useRef<Group>(null),arm=useRef<Group>(null),otherArm=useRef<Group>(null);
 const phase=useRef(0); const target=useRef(new Vector3());
 useFrame((_,delta)=>{
  if(!root.current)return;
  target.current.set(agent.position[0],0,agent.position[1]);
  root.current.position.lerp(target.current,1-Math.exp(-delta*18));
  positions.current[name].copy(root.current.position);
  const angle=Math.atan2(Math.sin(agent.heading-root.current.rotation.y),Math.cos(agent.heading-root.current.rotation.y));
  root.current.rotation.y+=angle*(1-Math.exp(-delta*12));
  if(paused)return;
  phase.current+=Math.min(delta,.08)*speed; const t=phase.current;
  const seated=!moving&&(place==='desk'||place==='sofa'||place==='meeting'||place==='bench')&&name!=='Rank';
  const celebrating=!moving&&agent.pose==='celebrate';
  if(body.current){body.current.position.y=moving?Math.sin(t*10)*.035:celebrating?Math.abs(Math.sin(t*5))*.22:seated?.25:Math.sin(t*2)*.012;body.current.rotation.x=!moving&&agent.pose==='sleep'?.25:0;}
  if(left.current)left.current.rotation.x=moving?Math.sin(t*10)*.48:seated?-1.1:0;
  if(right.current)right.current.rotation.x=moving?-Math.sin(t*10)*.48:seated?-1.1:0;
  if(arm.current)arm.current.rotation.x=moving?Math.sin(t*10)*.4:celebrating||agent.pose==='stretch'?-2.5:agent.pose==='coffee'?-1.15+Math.sin(t*2)*.16:agent.pose==='typing'?-.8+Math.sin(t*13)*.08:agent.pose==='water'?-.8+Math.sin(t*3)*.15:agent.pose==='count'?-.6+Math.sin(t*8)*.2:agent.pose==='inspect'||agent.pose==='chart'||agent.pose==='game'||agent.pose==='phone'?-.65:0;
  if(otherArm.current)otherArm.current.rotation.x=celebrating||agent.pose==='stretch'?-2.5:moving?-Math.sin(t*10)*.3:0;
 });
 return <group ref={root} visible={!agent.hiddenUntil||simTime>=agent.hiddenUntil} position={[desks[name][0],0,desks[name][1]+.5]} rotation={[0,Math.PI,0]} onClick={e=>{e.stopPropagation();onSelect(name)}} onPointerOver={()=>document.body.style.cursor='pointer'} onPointerOut={()=>document.body.style.cursor='auto'}>
 <group ref={body}><group ref={left} position={[-.13,.37,0]}><Round p={[0,-.13,0]} s={[.19,.34,.2]} c="#405a57"/><Round p={[0,-.28,.055]} s={[.22,.12,.3]} c="#faf0d7" radius={.04}/></group><group ref={right} position={[.13,.37,0]}><Round p={[0,-.13,0]} s={[.19,.34,.2]} c="#405a57"/><Round p={[0,-.28,.055]} s={[.22,.12,.3]} c="#faf0d7" radius={.04}/></group>
 <Round p={[0,.59,0]} s={[.51,.5,.33]} c={profiles[name].color}/><Block p={[0,.69,.18]} s={[.15,.2,.025]} c="#f3edd7"/>{name==='Beam'&&[-.18,.18].map(x=><Block key={x} p={[x,.58,.177]} s={[.06,.35,.018]} c="#f4cf64"/>)}{name==='Eco'&&<Ball p={[.15,.67,.18]} s={.057} c="#c9e9a6"/>}
 <group ref={arm} position={[-.31,.72,0]}><Round p={[0,-.14,0]} s={[.17,.34,.21]} c={profiles[name].color}/><Ball p={[0,-.33,0]} s={.091} c="#efd0ad"/>{agent.pose==='coffee'&&!moving&&<Mug p={[0,-.34,.08]} c="#f3e4bc"/>}</group><group ref={otherArm} position={[.31,.72,0]}><Round p={[0,-.15,0]} s={[.17,.34,.21]} c={profiles[name].color}/><Ball p={[0,-.34,0]} s={.09} c="#efd0ad"/></group>
 <Round p={[0,1.08,0]} s={[.66,.61,.55]} c="#f3d8b8" radius={.19}/><Round p={[0,1.33,-.06]} s={[.68,.22,.5]} c={name==='Kyaw'?'#4a3048':name==='Carbon'?'#466b53':name==='Durability'?'#765342':name==='Maintain'?'#71594b':name==='Environment'?'#566263':name==='Eco'?'#5a6650':name==='Rank'?'#384655':name==='Check'?'#777e80':name==='Cash'?'#956239':'#66564a'} radius={.1}/><Ball p={[-.343,1.07,0]} s={.073} c="#efcaaa"/><Ball p={[.343,1.07,0]} s={.073} c="#efcaaa"/>
 {[-.125,.125].map(x=><group key={x}><Ball p={[x,1.09,.275]} s={.036} c="#344b43"/><Ball p={[x-.014,1.103,.302]} s={.01} c="#fff"/><mesh position={[x*1.5,.995,.274]} scale={[1,.5,1]}><sphereGeometry args={[.052,10,8]}/><meshStandardMaterial color="#e6aa91"/></mesh></group>)}<mesh position={[0,1.008,.282]} rotation={[0,0,Math.PI]}><torusGeometry args={[.047,.013,6,12,Math.PI]}/><meshStandardMaterial color="#8e6653"/></mesh>
 {(name==='Atlas'||name==='Check')&&<><Block p={[0,1.09,.309]} s={[.075,.022,.025]} c="#595b4e"/>{[-.125,.125].map(x=><mesh key={x} position={[x,1.09,.301]}><torusGeometry args={[.079,.012,6,16]}/><meshStandardMaterial color="#595b4e"/></mesh>)}</>}
 {name==='Check'&&<group position={[.37,.48,.19]} rotation={[-.25,0,-.2]}><Block s={[.25,.36,.045]} c="#87735c"/><Block p={[0,0,.027]} s={[.21,.29,.01]} c="#f4eedc"/>{[0,1,2].map(i=><Block key={i} p={[0,.08-i*.07,.036]} s={[.13,.012,.01]} c="#9c8bb1"/>)}</group>}
 {name==='Cash'&&<group position={[.36,.45,.2]}><Round s={[.25,.34,.06]} c="#f4d778" radius={.02}/><Block p={[0,.075,.038]} s={[.18,.075,.01]} c="#355e55"/>{[0,1,2,3,4,5].map(i=><Block key={i} p={[-.065+i%3*.065,-.025-Math.floor(i/3)*.07,.04]} s={[.035,.035,.015]} c="#faf3d9"/>)}</group>}
 {name==='Rank'&&<><Block p={[0,.78,.18]} s={[.1,.05,.03]} c="#c0d6ed"/><group position={[.39,.46,.17]}><Round s={[.3,.35,.055]} c="#394c68" radius={.025}/><Block p={[0,0,.032]} s={[.25,.29,.008]} c="#e0eaf1"/>{[0,1,2].map(i=><Block key={i} p={[-.075+i*.075,-.04+i*.023,.04]} s={[.04,.1+i*.05,.008]} c={i===1?'#85a895':'#819dca'}/>)}</group></>}
 {agent.pose==='water'&&!moving&&<group position={[-.38,.42,.19]}><Cylinder p={[0,0,0]} r={.105} h={.18} c="#8bb5a9"/><Block p={[.14,.035,0]} s={[.2,.045,.045]} c="#8bb5a9"/><Ball p={[.22,-.06,0]} s={.025} c="#a4d2e0"/></group>}
 {name==='Beam'&&<><mesh position={[0,1.36,0]} scale={[1,.55,1]} castShadow><sphereGeometry args={[.39,12,8,0,Math.PI*2,0,Math.PI/2]}/><meshStandardMaterial color="#f0c55e"/></mesh><Cylinder p={[0,1.35,.04]} r={.4} h={.06} c="#f4cd72"/><Block p={[0,1.5,0]} s={[.06,.055,.43]} c="#f6d888"/></>}
 {name==='Eco'&&<><Ball p={[0,1.54,-.05]} s={.16} c="#5a6650"/><mesh position={[.16,1.48,0]} rotation={[0,0,-.7]} scale={[.06,.14,.045]}><sphereGeometry args={[1,8,6]}/><meshStandardMaterial color="#a8c77b"/></mesh></>}
 {name==='Kyaw'&&<><mesh position={[0,1.53,0]}><coneGeometry args={[.29,.23,5]}/><meshStandardMaterial color="#f5c668"/></mesh><Ball p={[0,1.67,0]} s={.085} c="#ffefad"/><Block p={[0,.78,.18]} s={[.16,.13,.02]} c="#ffe4a1"/></>}
 {name==='Carbon'&&<Ball p={[.18,.75,.19]} s={.06} c="#a8d96e"/>}{name==='Durability'&&<Block p={[.18,.69,.18]} s={[.13,.16,.02]} c="#f6d58d"/>}{name==='Maintain'&&<Block p={[.3,.36,.16]} s={[.09,.24,.06]} c="#d9dde0"/>}{name==='Environment'&&<Ball p={[-.18,.73,.18]} s={.07} c="#9bdac4"/>}
 </group>
 <Html position={[0,2.85,0]} center distanceFactor={12} zIndexRange={[24,21]}><div className="speech-bubble" style={{display:agent.bubble?'block':'none'}}><b>{name}</b>{agent.bubble}</div></Html>
 <Html position={[0,2.06,0]} center distanceFactor={13} zIndexRange={[20,0]}><button style={{display:labels?'flex':'none'}} className={'character-label '+name.toLowerCase()} onClick={e=>{e.stopPropagation();onSelect(name)}}><strong>{name==='Kyaw'?'KYAW Htet Zaw':name.toUpperCase()}</strong><span>{profiles[name].role}</span><small className={'label-state state-'+agent.state.toLowerCase().replace(' ','-')}>{name==='Kyaw'&&agent.pose==='sleep'?'😴 CEO MODE':(name==='Kyaw'?'👑 ':stateIcons[agent.state]+' ')+agent.state}</small></button></Html>
 </group>
}
function CameraRig({request}:{request:FocusRequest}){const controls=useRef<React.ComponentRef<typeof OrbitControls>>(null);const animating=useRef(false);const desired=useRef(new Vector3());const target=useRef(new Vector3());const {camera,size}=useThree();const fit=Math.max(1,.95/(size.width/size.height));useEffect(()=>{target.current.set(...request.point);if(request.home)desired.current.set(45,46,51).multiplyScalar(fit);else if(request.zoom){desired.current.copy(camera.position).sub(controls.current?.target??new Vector3()).multiplyScalar(request.zoom).add(target.current)}else desired.current.copy(target.current).add(request.room?new Vector3(15,14,17):new Vector3(8,7.5,9));animating.current=true;},[request,fit]);useFrame((_,dt)=>{if(controls.current){controls.current.target.x=Math.max(-11,Math.min(25,controls.current.target.x));controls.current.target.z=Math.max(-7,Math.min(29,controls.current.target.z));}if(animating.current&&controls.current){camera.position.lerp(desired.current,1-Math.exp(-dt*4));controls.current.target.lerp(target.current,1-Math.exp(-dt*4));controls.current.update();if(camera.position.distanceTo(desired.current)<.015)animating.current=false;}});return <OrbitControls ref={controls} makeDefault target={[6,.5,9]} minDistance={6} maxDistance={130} minPolarAngle={.3} maxPolarAngle={1.4} enableDamping dampingFactor={.08} onStart={()=>animating.current=false}/>}
class SceneBoundary extends React.Component<{children:React.ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true}}render(){return this.state.failed?<div className="scene-error"><Box size={40}/><h2>The lab needs WebGL</h2><p>Enable hardware acceleration in your browser, then reload to visit your team.</p><button onClick={()=>window.location.reload()}>Reload the lab</button></div>:this.props.children}}
function Avatar({name}:{name:Person}){return <span className={'avatar avatar-'+name.toLowerCase()}><span>{profiles[name].avatar}</span></span>}
const StableOffice=React.memo(Office);
function Celebration({paused,speed}:{paused:boolean;speed:number}){const root=useRef<Group>(null),phase=useRef(0);const bits=React.useMemo(()=>Array.from({length:42},(_,i)=>({x:Math.sin(i*13.7)*2.8,z:Math.cos(i*8.1)*2.7,color:['#ffd06d','#f398a9','#85cbbb','#a89cdb','#fff1bb'][i%5]})),[]);useFrame((_,dt)=>{if(paused||!root.current)return;phase.current+=dt*speed;root.current.children.forEach((piece,i)=>{piece.position.y=.6+((i*.19-phase.current*.7+20)%3.3);piece.rotation.z+=dt*.7})});return <group ref={root} position={[3.4,0,10.2]}>{bits.map((bit,i)=><mesh key={i} position={[bit.x,1,bit.z]} rotation={[i*.12,0,i*.16]}><planeGeometry args={[.13,.2]}/><meshBasicMaterial color={bit.color} side={2}/></mesh>)}</group>}
export default function App(){
 const [tab,setTab]=useState('OFFICE'),[paused,setPaused]=useState(false),[speed,setSpeed]=useState(1),[labels,setLabels]=useState(true),[selected,setSelected]=useState<Person|null>(null),[help,setHelp]=useState(false),[bridge,setBridge]=useState(false);
 const {simulation,dispatch}=useSimulation(paused,speed); const sidebar=useRef<HTMLElement>(null);
 const [request,setRequest]=useState<FocusRequest>({point:[6,.5,9],key:0,home:true});
 const positions=useRef<Record<Person,Vector3>>(Object.fromEntries(everyone.map(name=>{const p=location(name,'desk');return [name,new Vector3(p[0],0,p[1])]})) as Record<Person,Vector3>);
 const select=useCallback((name:Person)=>{setSelected(name);setBridge(false);sidebar.current?.scrollTo({top:0,behavior:'smooth'});setRequest({point:[positions.current[name].x,.7,positions.current[name].z],key:Date.now()})},[]);
 const home=()=>{setRequest({point:[6,.5,9],key:Date.now(),home:true});setSelected(null);setBridge(false)};
 const focusRoom=useCallback((room:Room)=>{const [x,z]=rooms[room];setRequest({point:[x,.5,z],key:Date.now(),room:true});setBridge(false);setSelected(null)},[]);
 const focusBridge=useCallback(()=>{setSelected(null);setBridge(true);setRequest({point:[-.3,.8,.05],key:Date.now()})},[]);
 useEffect(()=>{const listener=(e:KeyboardEvent)=>{if(e.code==='Space' && e.target instanceof HTMLButtonElement)return;if(e.code==='Space'){e.preventDefault();setPaused(p=>!p)}if(e.key==='Escape'){setHelp(false);setTab('OFFICE');home()}if(e.key.toLowerCase()==='h')home()};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener)},[]);
 return <div className="app"><header><a className="brand" href="#" onClick={e=>{e.preventDefault();setTab('OFFICE');home()}}><span className="brand-icon"><Box size={25} strokeWidth={1.6}/></span><span>AGENTIC AI <b>OFFICE</b><small>FOR BOX GIRDER BRIDGE DESIGN</small></span></a><nav aria-label="Main navigation">{['OFFICE','TEAM','PROJECTS','DESIGN BOARD','NEEDS YOU','CEO'].map(t=><button className={tab===t?'active':''} key={t} onClick={()=>setTab(t)}>{t}{t==='NEEDS YOU'&&simulation.project.status==='NEEDS YOU'&&<span className="nav-dot needs-dot"/>}</button>)}</nav><div className="header-right"><span className="simulation-pill"><span/> SIMULATION</span><button className="icon-btn help" aria-label="How to play" onClick={()=>setHelp(true)}><HelpCircle size={20}/></button></div></header>
 <main><div className="stage"><div className="office-heading"><div className="eyebrow"><span/> YOUR LITTLE WORLD</div><h1>Good ideas live here<span>.</span></h1><p>A miniature company full of big pretend ideas.</p></div><button className="day-chip workflow-chip" onClick={()=>setTab(simulation.project.status==='NEEDS YOU'?'NEEDS YOU':'PROJECTS')}><Sun size={18}/><div>{simulation.project.id} <span>·</span> {simulation.project.status==='COMPLETE'?'Complete':simulation.project.issue==='ceoApproval'?'CEO Review':simulation.project.stage}<small>{simulation.project.status==='NEEDS YOU'?'A GAME DECISION NEEDS YOU':simulation.project.phase.toUpperCase()} · SIMULATION</small></div><ChevronRight size={13}/></button>
 <SceneBoundary><Canvas shadows dpr={[1,1.35]} camera={{position:[45,46,51],fov:36,far:250}} gl={{antialias:true}}><color attach="background" args={['#dcf1cf']}/><ambientLight intensity={1.45}/><hemisphereLight args={['#fff3d5','#a3c881',.85]}/><directionalLight position={[-9,19,11]} intensity={2.05} color="#ffe7c3" castShadow shadow-mapSize={[1024,1024]} shadow-camera-left={-28} shadow-camera-right={28} shadow-camera-top={28} shadow-camera-bottom={-28} shadow-normalBias={.055}/><Suspense fallback={null}><StableOffice onBridge={focusBridge} spans={simulation.project.spans} span={simulation.project.span} width={simulation.project.width} depth={simulation.project.geometry?.depth??2.4}/><WorldExpansion onRoom={focusRoom}/>{everyone.map(name=><Character key={name} agent={simulation.agents[name]} paused={paused} speed={speed} labels={labels} onSelect={select} positions={positions} simTime={simulation.time}/>)}{simulation.celebrationUntil>simulation.time&&<Celebration paused={paused} speed={speed}/>}<ContactShadows position={[0,-.55,0]} opacity={.18} scale={24} blur={2.4} far={10} resolution={256} frames={1}/><CameraRig request={request}/></Suspense></Canvas></SceneBoundary>
 <div className="room-nav" aria-label="Focus department">{(Object.keys(rooms) as Room[]).map(room=><button key={room} onClick={()=>focusRoom(room)}>{room.toUpperCase()}</button>)}</div>
 <div className="scene-corner"><span className="live-dot"/>{paused?'TAKING A BREATHER':'THE LAB IS ALIVE'}<span className="corner-divider"/>10 agents + 1 CEO · endless curiosity</div>
 <div className="view-controls"><button className="icon-btn" title="Zoom in" aria-label="Zoom in" onClick={()=>setRequest(r=>({...r,home:false,zoom:.8,key:Date.now()}))}><Plus size={18}/></button><button className="icon-btn" title="Zoom out" aria-label="Zoom out" onClick={()=>setRequest(r=>({...r,home:false,zoom:1.2,key:Date.now()}))}><Minus size={18}/></button><span/><button className="icon-btn" title="Reset view (H)" aria-label="Reset view" onClick={home}><Focus size={19}/></button><button className={'icon-btn '+(!labels?'muted':'')} title="Toggle name tags" aria-label="Toggle name tags" aria-pressed={labels} onClick={()=>setLabels(v=>!v)}><Users size={18}/></button></div>
 <div className="camera-hint"><Compass size={14}/> Drag to orbit <span>·</span> Scroll to zoom <span>·</span> Click to say hello</div>
 </div><aside ref={sidebar} className="workflow-sidebar">
 <div className="team-heading"><div><span className="eyebrow">THE PEOPLE BEHIND THE POSSIBILITIES</span><h2>Your little company <span>11</span></h2></div><Users size={20}/></div>
 {selected&&<><div className="selected-close"><button className="icon-btn" aria-label="Close character details" onClick={()=>setSelected(null)}><X size={16}/></button></div>{selected==='Kyaw'?<CEOPanel agent={simulation.agents.Kyaw} dispatch={dispatch} onFocus={()=>select('Kyaw')} onDashboard={()=>setTab('CEO')}/>:<AgentPanel agent={simulation.agents[selected]} onTask={()=>setTab('DESIGN BOARD')} onFocus={()=>select(selected)} onBreak={()=>{dispatch({type:'break',name:selected});setPaused(false)}} onResume={()=>dispatch({type:'resume',name:selected})}/>} </>}
 <div className="department-label">LEADERS & CORE TEAM</div><div className="team-list">{people.map(name=>{const agent=simulation.agents[name];return <button key={name} className={'team-card '+(selected===name?'selected':'')} onClick={()=>select(name)}><Avatar name={name}/><div><h3>{name}<span className="agent-tag">AI</span></h3><p>{profiles[name].role}</p><span className={'agent-status state-'+agent.state.toLowerCase().replace(' ','-')}>{stateIcons[agent.state]} {agent.state}{agent.state==='WORKING'?' · '+agent.progress+'%':''}</span></div><ChevronRight className="team-chevron" size={17}/></button>})}</div><div className="department-label">ECO'S SUSTAINABILITY CREW</div><div className="team-list">{workers.map(name=>{const agent=simulation.agents[name];return <button key={name} className={'team-card '+(selected===name?'selected':'')} onClick={()=>select(name)}><Avatar name={name}/><div><h3>{name}<span className="agent-tag">AI</span></h3><p>{profiles[name].role}</p><span className={'agent-status state-'+agent.state.toLowerCase().replace(' ','-')}>{stateIcons[agent.state]} {agent.state}{agent.state==='WORKING'?' · '+Math.round(agent.progress)+'%':''}</span></div><ChevronRight className="team-chevron" size={17}/></button>})}</div><div className="department-label">CEO CORNER 👑</div><div className="team-list"><button className={'team-card '+(selected==='Kyaw'?'selected':'')} onClick={()=>select('Kyaw')}><Avatar name="Kyaw"/><div><h3>KYAW Htet Zaw<span className="agent-tag">CEO</span></h3><p>Chief Executive Officer</p><span className="agent-status">👑 {simulation.agents.Kyaw.state} · 14% productive</span></div><ChevronRight className="team-chevron" size={17}/></button></div>
 {bridge&&<div className="model-note">This toy bridge changes its visible span count and proportions with the fictional project. It represents no engineering design.</div>}
 <WorkflowCard simulation={simulation} dispatch={dispatch} onOpen={()=>setTab(simulation.project.status==='NEEDS YOU'?'NEEDS YOU':'PROJECTS')} onModel={focusBridge}/>
 <section className="activity"><div className="section-top"><h3><Radio size={16}/> Lab happenings</h3><span>{paused?'PAUSED':'LIVE'}</span></div><div className="events">{simulation.events.slice(0,4).map(e=><div className="event" key={e.id}><span className="event-dot" style={{background:profiles[e.name].color}}/><p><b>{e.name}</b> {e.text}<small>{Math.floor(simulation.time-e.time)<5?'Just now':Math.floor(simulation.time-e.time)+' game seconds ago'}</small></p></div>)}</div></section><div className="cozy-note"><Sparkles size={17}/><span>Small steps. Thoughtful pretend bridges.</span></div>
 </aside></main>
 <footer><div className="playback"><button className="play-btn" aria-label={paused?'Resume simulation':'Pause simulation'} onClick={()=>setPaused(v=>!v)}>{paused?<Play size={16}/>:<Pause size={16}/>}</button><span>{paused?'Paused':'Office life'}<small>{paused?'Everyone deserves a little break':'Happily doing their thing'}</small></span><div className="speed-picker">{[1,2,3].map(s=><button key={s} className={speed===s?'active':''} onClick={()=>setSpeed(s)} aria-label={`${s} times speed`}>{s}×</button>)}</div></div><p className="disclaimer"><Leaf size={16}/> Agentic AI Office for Box Girder Bridge Design is a fictional simulation game. <span>It does not perform structural engineering design and must not be used for engineering decisions.</span></p><span className="version">MADE OF LITTLE POSSIBILITIES <span>✳</span></span></footer>
 {tab!=='OFFICE'&&<WorkflowWindow tab={tab} simulation={simulation} dispatch={dispatch} selected={selected} onSelect={select} onClose={()=>setTab('OFFICE')} onNavigate={setTab}/>}
 {help&&<div className="modal-backdrop" onClick={()=>setHelp(false)}><section className="modal help-modal" role="dialog" aria-modal="true" aria-label="Welcome to the lab" onClick={e=>e.stopPropagation()}><button className="close-modal icon-btn" autoFocus aria-label="Close help" onClick={()=>setHelp(false)}><X size={20}/></button><span className="modal-illustration"><Sparkles size={35}/></span><h2>Make yourself at home.</h2><p>Ten little agents move a fictional project through four departments and bring decisions to you. Rank shortlists three game alternatives; Kyaw gives the final CEO review, assuming he is awake. Watch the handoffs, explore the dashboards, and run this slightly dysfunctional company.</p><ul><li><RotateCcw size={18}/><span><b>Explore the office</b>Drag to rotate, scroll or pinch to zoom, right-drag to pan.</span></li><li><Users size={18}/><span><b>Meet the team</b>Click an agent to view their task, save their progress for a coffee break, or focus the camera.</span></li><li><Maximize2 size={18}/><span><b>Set your own pace</b>Space pauses. H resets the camera. 1×, 2×, 3× adjust life’s pace.</span></li></ul><div className="help-notice">Everything here is make-believe. This is a visual game, never a structural engineering tool.</div><button className="primary-btn" onClick={()=>setHelp(false)}>Let’s wander <ArrowUpRight size={16}/></button></section></div>}
 </div>
}
